[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "HumanActivityDetection"
version = "1.0.4"
description = "Human Activity Detection using LSTM"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "Vinay" }
]

dependencies = [
    "Flask==2.2.5",
    "Flask-Bootstrap==3.3.7.1",
    "Flask-Uploads==0.2.1",

    "numpy==1.26.4",
    "opencv-python==4.10.0.84",
    "torchvision==0.14.1",
    "torchmetrics==0.11.4",
    "pytorch-lightning==1.9.5",

    "PyYAML==6.0.2",
    "Werkzeug==2.2.3",

    "azure-storage-blob==12.30.0",
    "azure-identity==1.25.3",

    "fvcore",
    "iopath",
    "pycocotools",
    "yacs",
    "hydra-core",
    "matplotlib",

    "setuptools==69.5.1"
]

[tool.setuptools]
py-modules = ["app"]
packages = ["src"]

[tool.setuptools.package-data]
src = ["*"]
